// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowManager owns the lifecycle of every webview window the app spawns —
 * the launcher and per-project editor windows. The frontend calls these
 * methods via Wails service bindings; main.go also drives the launcher at
 * startup and on dock reactivation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenLauncher creates the launcher window or focuses an existing one.
 * Returns nil for now — the error in the signature is included so Wails
 * emits a Promise-returning binding.
 */
export function OpenLauncher(): $CancellablePromise<void> {
    return $Call.ByID(2228267601);
}

/**
 * OpenProject creates an editor window for the given project id (or focuses
 * an existing one). After the editor opens, the launcher is closed.
 */
export function OpenProject(projectId: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2912764030, projectId, name);
}
